-- Esquema inicial para Oracle (perfil "oracle").
-- Mismo modelo que db/migration/V1__esquema_inicial.sql (PostgreSQL y H2), con los tipos propios de Oracle:
--   BIGINT  -> NUMBER(19)        (Oracle no tiene BIGINT; NUMBER(19) es lo que Hibernate espera para un Long)
--   VARCHAR -> VARCHAR2(n CHAR)  (longitud en caracteres y no en bytes, para que "ñ" o "à" cuenten como uno)
-- Las columnas identidad (GENERATED BY DEFAULT AS IDENTITY) existen en Oracle desde la versión 12c.
--
-- Límite de 4000 bytes: aunque se declare en caracteres, un VARCHAR2 no puede superar 4000 bytes
-- (salvo MAX_STRING_SIZE=EXTENDED). En UTF-8 un carácter ocupa hasta 4 bytes, por eso los textos
-- libres (descripción y comentarios) se limitan a 1000 caracteres en toda la aplicación: así caben
-- siempre. La alternativa para textos más largos sería un CLOB.

CREATE TABLE usuarios (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(100 CHAR) NOT NULL,
    email       VARCHAR2(150 CHAR) NOT NULL,
    password    VARCHAR2(100 CHAR) NOT NULL,
    rol         VARCHAR2(20 CHAR)  NOT NULL,
    fecha_alta  TIMESTAMP          NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT ck_usuarios_rol CHECK (rol IN ('USUARIO', 'TECNICO'))
);

CREATE TABLE incidencias (
    id                   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo               VARCHAR2(150 CHAR)  NOT NULL,
    descripcion          VARCHAR2(1000 CHAR) NOT NULL,
    estado               VARCHAR2(20 CHAR)   NOT NULL,
    prioridad            VARCHAR2(20 CHAR)   NOT NULL,
    creador_id           NUMBER(19)          NOT NULL,
    tecnico_id           NUMBER(19),
    fecha_creacion       TIMESTAMP           NOT NULL,
    fecha_actualizacion  TIMESTAMP           NOT NULL,
    fecha_resolucion     TIMESTAMP,
    CONSTRAINT fk_incidencias_creador FOREIGN KEY (creador_id) REFERENCES usuarios (id),
    CONSTRAINT fk_incidencias_tecnico FOREIGN KEY (tecnico_id) REFERENCES usuarios (id),
    CONSTRAINT ck_incidencias_estado CHECK (estado IN ('ABIERTA', 'EN_CURSO', 'RESUELTA', 'CERRADA')),
    CONSTRAINT ck_incidencias_prioridad CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA'))
);

CREATE TABLE comentarios (
    id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto          VARCHAR2(1000 CHAR) NOT NULL,
    incidencia_id  NUMBER(19)          NOT NULL,
    autor_id       NUMBER(19)          NOT NULL,
    fecha          TIMESTAMP           NOT NULL,
    CONSTRAINT fk_comentarios_incidencia FOREIGN KEY (incidencia_id) REFERENCES incidencias (id) ON DELETE CASCADE,
    CONSTRAINT fk_comentarios_autor FOREIGN KEY (autor_id) REFERENCES usuarios (id)
);

-- Igual que PostgreSQL, Oracle no indexa automáticamente las claves foráneas
CREATE INDEX idx_incidencias_creador ON incidencias (creador_id);
CREATE INDEX idx_incidencias_tecnico ON incidencias (tecnico_id);
CREATE INDEX idx_incidencias_estado ON incidencias (estado);
CREATE INDEX idx_comentarios_incidencia ON comentarios (incidencia_id);
