-- Esquema inicial. SQL estándar para que funcione igual en PostgreSQL y en H2 (tests).

CREATE TABLE usuarios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL,
    email       VARCHAR(150) NOT NULL,
    password    VARCHAR(100) NOT NULL,
    rol         VARCHAR(20)  NOT NULL,
    fecha_alta  TIMESTAMP    NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT ck_usuarios_rol CHECK (rol IN ('USUARIO', 'TECNICO'))
);

CREATE TABLE incidencias (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo               VARCHAR(150)  NOT NULL,
    descripcion          VARCHAR(4000) NOT NULL,
    estado               VARCHAR(20)   NOT NULL,
    prioridad            VARCHAR(20)   NOT NULL,
    creador_id           BIGINT        NOT NULL,
    tecnico_id           BIGINT,
    fecha_creacion       TIMESTAMP     NOT NULL,
    fecha_actualizacion  TIMESTAMP     NOT NULL,
    fecha_resolucion     TIMESTAMP,
    CONSTRAINT fk_incidencias_creador FOREIGN KEY (creador_id) REFERENCES usuarios (id),
    CONSTRAINT fk_incidencias_tecnico FOREIGN KEY (tecnico_id) REFERENCES usuarios (id),
    CONSTRAINT ck_incidencias_estado CHECK (estado IN ('ABIERTA', 'EN_CURSO', 'RESUELTA', 'CERRADA')),
    CONSTRAINT ck_incidencias_prioridad CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA'))
);

CREATE TABLE comentarios (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto          VARCHAR(2000) NOT NULL,
    incidencia_id  BIGINT        NOT NULL,
    autor_id       BIGINT        NOT NULL,
    fecha          TIMESTAMP     NOT NULL,
    CONSTRAINT fk_comentarios_incidencia FOREIGN KEY (incidencia_id) REFERENCES incidencias (id) ON DELETE CASCADE,
    CONSTRAINT fk_comentarios_autor FOREIGN KEY (autor_id) REFERENCES usuarios (id)
);

-- Índices para las consultas más habituales (listado filtrado y comentarios de una incidencia)
CREATE INDEX idx_incidencias_creador ON incidencias (creador_id);
CREATE INDEX idx_incidencias_tecnico ON incidencias (tecnico_id);
CREATE INDEX idx_incidencias_estado ON incidencias (estado);
CREATE INDEX idx_comentarios_incidencia ON comentarios (incidencia_id);
